language: php
php:
  - 7.4
  - 8.0
env:
  matrix:
    - TEST_SUITE=static
    - TEST_SUITE=unit
  global:
    - XDEBUG_MODE=coverage
before_script:
  - composer install
script:
  - mkdir -p build/logs
  - if [ $TEST_SUITE == "static" ]; then vendor/bin/phpcs .; fi
  - if [ $TEST_SUITE == "static" ]; then vendor/bin/phpmd src text cleancode,design,naming,unusedcode; fi
  - if [ $TEST_SUITE == "unit" ]; then vendor/bin/phpunit; fi
  - if [ $TEST_SUITE == "unit" ]; then wget https://gist.githubusercontent.com/manuelcanepa/27fc542807b1e3cb4cdefa6bda2d4b34/raw/6824c6332c023f5f729a8958a1df9f5150568cf4/coverage-checker.php; fi
  - if [ $TEST_SUITE == "unit" ]; then php coverage-checker.php build/logs/clover.xml 80; fi
